import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeftIcon, GlobeIcon, MessageSquareIcon } from "lucide-react";

import { cn } from "cn";
import { getSharedChat } from "@/db/queries";
import { buttonVariants } from "@/components/ui/button";
import { Markdown } from "@/components/chat/markdown";
import { ProviderMark } from "@/components/chat/provider-mark";
import { ThemeToggle } from "@/components/theme-toggle";

function modelLabel(id: string) {
  if (!id) return "Assistant";
  return id.includes("/") ? id.slice(id.lastIndexOf("/") + 1) : id;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const shared = await getSharedChat(id);
  if (!shared) return { title: "Shared Chat Not Found - OmniChat" };

  return {
    title: `${shared.title} - OmniChat`,
    description: `Public chat transcript for "${shared.title}" generated by ${modelLabel(shared.modelId)}.`,
  };
}

export default async function SharedChatPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const shared = await getSharedChat(id);

  if (!shared) {
    return (
      <div className="flex min-h-svh flex-col items-center justify-center p-6 text-center">
        <div className="flex size-12 items-center justify-center rounded-2xl bg-muted text-muted-foreground">
          <GlobeIcon className="size-6" />
        </div>
        <h1 className="mt-4 text-xl font-semibold">Shared chat not found</h1>
        <p className="mt-1.5 max-w-sm text-sm text-muted-foreground">
          This shared link may have been deleted, or the URL might be incorrect.
        </p>
        <Link
          href="/"
          className={cn(buttonVariants({ variant: "default" }), "mt-6 gap-2")}
        >
          <ArrowLeftIcon className="size-4" />
          Go to OmniChat
        </Link>
      </div>
    );
  }

  return (
    <div className="flex min-h-svh flex-col bg-background text-foreground">
      {/* Top Banner */}
      <header className="sticky top-0 z-20 flex h-14 shrink-0 items-center justify-between border-b bg-background/80 px-4 backdrop-blur">
        <div className="flex items-center gap-2.5">
          <Link
            href="/"
            className="flex items-center gap-2 font-semibold text-sm hover:opacity-80 transition-opacity"
          >
            <div className="flex size-7 items-center justify-center rounded-lg bg-primary text-primary-foreground text-xs font-bold">
              OC
            </div>
            <span>OmniChat</span>
          </Link>
          <span className="rounded-md bg-muted px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
            Shared Snapshot
          </span>
        </div>

        <div className="flex items-center gap-2">
          <ThemeToggle />
          <Link
            href="/"
            className={cn(buttonVariants({ size: "sm" }), "gap-1.5")}
          >
            <MessageSquareIcon className="size-3.5" />
            <span>Start chatting</span>
          </Link>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-8">
        <div className="mb-8 border-b pb-6">
          <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">
            {shared.title}
          </h1>
          <div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
            <div className="flex items-center gap-1.5">
              <ProviderMark modelId={shared.modelId} className="size-4" />
              <span className="font-medium text-foreground">
                {modelLabel(shared.modelId)}
              </span>
            </div>
            <span>•</span>
            <span>Shared {shared.updatedAt}</span>
            <span>•</span>
            <span>{shared.messages.length} messages</span>
          </div>
        </div>

        <div className="space-y-6">
          {shared.messages.map((message) => {
            const isUser = message.role === "user";

            if (isUser) {
              return (
                <div
                  key={message.id}
                  className="flex flex-col items-end gap-1.5 py-2"
                >
                  <div className="rounded-2xl rounded-tr-sm bg-muted px-4 py-2.5 text-[15px] leading-7 whitespace-pre-wrap max-w-[min(42rem,85%)]">
                    {message.content}
                  </div>
                  <span className="text-[11px] text-muted-foreground">
                    {message.createdAt}
                  </span>
                </div>
              );
            }

            const model = message.modelId ?? shared.modelId;

            return (
              <div key={message.id} className="flex gap-3 py-2">
                <ProviderMark modelId={model} className="mt-1 size-7" />
                <div className="flex min-w-0 flex-1 flex-col gap-1.5">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-semibold">
                      {modelLabel(model)}
                    </span>
                    <span className="text-[11px] text-muted-foreground">
                      {message.createdAt}
                    </span>
                  </div>
                  <div className="relative">
                    <Markdown content={message.content} />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t py-6 text-center text-xs text-muted-foreground">
        Shared publicly via{" "}
        <Link href="/" className="font-medium text-foreground hover:underline">
          OmniChat
        </Link>
      </footer>
    </div>
  );
}
